### PR TITLE
[WIP] Move all files into coldsteeltools directory and change imports

### PR DESCRIPTION
**Pull request by ghost**
Now that it's a proper module, all the internal imports had to change as
well.  I chose to use relative imports rather than absolute except in
the cs3Tools.py file, since it doesn't necessarily have to be right next
to the source.

I would have preferred to make these 2 changes separately, but
I couldn't make it work. I hope that's ok.

Please let me know if you'd prefer absolute imports instead.

In some places i had to use `...` and that should count as a code smell. It's kind of a rule to keep in mind.
If you have to use more than 2 `.` in your relative import, then you should rethink how your code is structured.

### CODE REVIEW

**Comment by ghost** [comment]
I realize there's still some outstanding work in regards to the `ref` files, and perhaps some others. Those should stay at the top level.  What do i have to do to test those, and which other ones do you think need changed

 Those paths are currently relative, but they should be absolute paths.

**Comment by nnguyen259** [comment]
ref jsons are used in the randomizer to generate the result

**Comment by ghost** [comment]
but what other files might break now that things are moved into the subdir? Like it's possible you'll need to adjust the cxfreeze config (although i didn't see the config file here)

**Comment by nnguyen259** [comment]
hmm another thing that might break is the script decompiler functionality since it uses the SenDecompiler in the `decompiler` folder. And yeah I'll need to check cx_freeze as well, and the config is in `setup.py`

**Comment by nnguyen259** [comment]
Sorry I haven't been around much, but the relative import in `unpacker/unpacker.py` could be broken as well. Same for the packer counterpart

**Pull request closed without merging**
